### ISSUE TITLE
How to setup aqua-microscanner-plugin to work with GitHub Organization pipeline?

### ISSUE THREAD

**Issue by brant4test** [jenkinsci/aqua-microscanner-plugin#12]
**Describe the solution you'd like**
Hi, Team,
How to setup aqua-microscanner-plugin to work with GitHub Organization pipeline?

Thanks!

**Comment by oranmoshai** [comment]
Hi brant4test,

The plugin support only jenkins. 
To implement in other CI solutions i recommend to use the docs: https://github.com/aquasecurity/microscanner

I am closing this thread let me know if you have other questions.
