### ISSUE TITLE
Jenkins is not passing in token into the plugin

### ISSUE THREAD

**Issue by pbradly** [jenkinsci/aqua-microscanner-plugin#17]
**Describe the bug**
I have installed version 1.0.6 of Aqua microscanner in our instance of jenkins and have defined the token value in Configure System -> Aqua MicroScanner. However it does not appear to be passing in the token as we are getting the following error in the jenkins logs;

Aqua MicroScanner in progress...
The command '/bin/sh -c ./microscanner ${token} --html' returned a non-zero code: 1
...
ERROR: failed fetching server information: request failed: Get https://microscanner.aquasec.com/api: EOF

**To Reproduce**
1. Generate a new token; docker run --rm -it aquasec/microscanner --register <email address>
2. Install Aqua MicroScaner plugin version 1.0.6
3. Define new token in Configure System -> Aqua MicroScanner.
4. Execute Aqua scan via JenkinsFile command; aquaMicroscanner imageName: image_name, notCompliesCmd: '', onDisallowed: 'ignore', outputFormat: 'html' where imageName is defined inside our jenkinsfile
5. Execute build in Jenkins

**Expected behavior**
Aqua scan is completed in image, and a html report is generated

**Comment by oranmoshai** [comment]
Hi @pbradly,

I tested with fresh Jenkins installation and didn't find any issue.

- What is your jenkins version ? 
- Please test this hard-coded pipeline: 
`node {
   sh "docker pull alpine:latest"
   aquaMicroscanner imageName: 'alpine:latest', notCompliesCmd: '', onDisallowed: 'ignore', outputFormat: 'html'
   
}`

- Please test your token using Dockerfile like described here: https://github.com/aquasecurity/microscanner

**Comment by oranmoshai** [comment]
I will close this for now please open if you have any issue 

Thank you
